/* soapServer.cpp
   Generated by gSOAP 2.8.9 from AmazonS3.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.9 2012-07-12 14:05:55 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:CreateBucket"))
		return soap_serve___ns1__CreateBucket(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:DeleteBucket"))
		return soap_serve___ns1__DeleteBucket(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetObjectAccessControlPolicy"))
		return soap_serve___ns1__GetObjectAccessControlPolicy(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetBucketAccessControlPolicy"))
		return soap_serve___ns1__GetBucketAccessControlPolicy(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SetObjectAccessControlPolicy"))
		return soap_serve___ns1__SetObjectAccessControlPolicy(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SetBucketAccessControlPolicy"))
		return soap_serve___ns1__SetBucketAccessControlPolicy(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetObject"))
		return soap_serve___ns1__GetObject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetObjectExtended"))
		return soap_serve___ns1__GetObjectExtended(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:PutObject"))
		return soap_serve___ns1__PutObject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:PutObjectInline"))
		return soap_serve___ns1__PutObjectInline(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:DeleteObject"))
		return soap_serve___ns1__DeleteObject(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:ListBucket"))
		return soap_serve___ns1__ListBucket(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:ListAllMyBuckets"))
		return soap_serve___ns1__ListAllMyBuckets(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:SetBucketLoggingStatus"))
		return soap_serve___ns1__SetBucketLoggingStatus(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:GetBucketLoggingStatus"))
		return soap_serve___ns1__GetBucketLoggingStatus(soap);
	if (!soap_match_tag(soap, soap->tag, "ns1:CopyObject"))
		return soap_serve___ns1__CopyObject(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__CreateBucket(struct soap *soap)
{	struct __ns1__CreateBucket soap_tmp___ns1__CreateBucket;
	_ns1__CreateBucketResponse ns1__CreateBucketResponse;
	ns1__CreateBucketResponse.soap_default(soap);
	soap_default___ns1__CreateBucket(soap, &soap_tmp___ns1__CreateBucket);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__CreateBucket(soap, &soap_tmp___ns1__CreateBucket, "-ns1:CreateBucket", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__CreateBucket(soap, soap_tmp___ns1__CreateBucket.ns1__CreateBucket, &ns1__CreateBucketResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__CreateBucketResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__CreateBucketResponse.soap_put(soap, "ns1:CreateBucketResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__CreateBucketResponse.soap_put(soap, "ns1:CreateBucketResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__DeleteBucket(struct soap *soap)
{	struct __ns1__DeleteBucket soap_tmp___ns1__DeleteBucket;
	_ns1__DeleteBucketResponse ns1__DeleteBucketResponse;
	ns1__DeleteBucketResponse.soap_default(soap);
	soap_default___ns1__DeleteBucket(soap, &soap_tmp___ns1__DeleteBucket);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__DeleteBucket(soap, &soap_tmp___ns1__DeleteBucket, "-ns1:DeleteBucket", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__DeleteBucket(soap, soap_tmp___ns1__DeleteBucket.ns1__DeleteBucket, &ns1__DeleteBucketResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__DeleteBucketResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__DeleteBucketResponse.soap_put(soap, "ns1:DeleteBucketResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__DeleteBucketResponse.soap_put(soap, "ns1:DeleteBucketResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetObjectAccessControlPolicy(struct soap *soap)
{	struct __ns1__GetObjectAccessControlPolicy soap_tmp___ns1__GetObjectAccessControlPolicy;
	_ns1__GetObjectAccessControlPolicyResponse ns1__GetObjectAccessControlPolicyResponse;
	ns1__GetObjectAccessControlPolicyResponse.soap_default(soap);
	soap_default___ns1__GetObjectAccessControlPolicy(soap, &soap_tmp___ns1__GetObjectAccessControlPolicy);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GetObjectAccessControlPolicy(soap, &soap_tmp___ns1__GetObjectAccessControlPolicy, "-ns1:GetObjectAccessControlPolicy", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetObjectAccessControlPolicy(soap, soap_tmp___ns1__GetObjectAccessControlPolicy.ns1__GetObjectAccessControlPolicy, &ns1__GetObjectAccessControlPolicyResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__GetObjectAccessControlPolicyResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetObjectAccessControlPolicyResponse.soap_put(soap, "ns1:GetObjectAccessControlPolicyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetObjectAccessControlPolicyResponse.soap_put(soap, "ns1:GetObjectAccessControlPolicyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetBucketAccessControlPolicy(struct soap *soap)
{	struct __ns1__GetBucketAccessControlPolicy soap_tmp___ns1__GetBucketAccessControlPolicy;
	_ns1__GetBucketAccessControlPolicyResponse ns1__GetBucketAccessControlPolicyResponse;
	ns1__GetBucketAccessControlPolicyResponse.soap_default(soap);
	soap_default___ns1__GetBucketAccessControlPolicy(soap, &soap_tmp___ns1__GetBucketAccessControlPolicy);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GetBucketAccessControlPolicy(soap, &soap_tmp___ns1__GetBucketAccessControlPolicy, "-ns1:GetBucketAccessControlPolicy", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetBucketAccessControlPolicy(soap, soap_tmp___ns1__GetBucketAccessControlPolicy.ns1__GetBucketAccessControlPolicy, &ns1__GetBucketAccessControlPolicyResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__GetBucketAccessControlPolicyResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetBucketAccessControlPolicyResponse.soap_put(soap, "ns1:GetBucketAccessControlPolicyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetBucketAccessControlPolicyResponse.soap_put(soap, "ns1:GetBucketAccessControlPolicyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SetObjectAccessControlPolicy(struct soap *soap)
{	struct __ns1__SetObjectAccessControlPolicy soap_tmp___ns1__SetObjectAccessControlPolicy;
	_ns1__SetObjectAccessControlPolicyResponse ns1__SetObjectAccessControlPolicyResponse;
	ns1__SetObjectAccessControlPolicyResponse.soap_default(soap);
	soap_default___ns1__SetObjectAccessControlPolicy(soap, &soap_tmp___ns1__SetObjectAccessControlPolicy);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SetObjectAccessControlPolicy(soap, &soap_tmp___ns1__SetObjectAccessControlPolicy, "-ns1:SetObjectAccessControlPolicy", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SetObjectAccessControlPolicy(soap, soap_tmp___ns1__SetObjectAccessControlPolicy.ns1__SetObjectAccessControlPolicy, &ns1__SetObjectAccessControlPolicyResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SetObjectAccessControlPolicyResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SetObjectAccessControlPolicyResponse.soap_put(soap, "ns1:SetObjectAccessControlPolicyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SetObjectAccessControlPolicyResponse.soap_put(soap, "ns1:SetObjectAccessControlPolicyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SetBucketAccessControlPolicy(struct soap *soap)
{	struct __ns1__SetBucketAccessControlPolicy soap_tmp___ns1__SetBucketAccessControlPolicy;
	_ns1__SetBucketAccessControlPolicyResponse ns1__SetBucketAccessControlPolicyResponse;
	ns1__SetBucketAccessControlPolicyResponse.soap_default(soap);
	soap_default___ns1__SetBucketAccessControlPolicy(soap, &soap_tmp___ns1__SetBucketAccessControlPolicy);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SetBucketAccessControlPolicy(soap, &soap_tmp___ns1__SetBucketAccessControlPolicy, "-ns1:SetBucketAccessControlPolicy", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SetBucketAccessControlPolicy(soap, soap_tmp___ns1__SetBucketAccessControlPolicy.ns1__SetBucketAccessControlPolicy, &ns1__SetBucketAccessControlPolicyResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SetBucketAccessControlPolicyResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SetBucketAccessControlPolicyResponse.soap_put(soap, "ns1:SetBucketAccessControlPolicyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SetBucketAccessControlPolicyResponse.soap_put(soap, "ns1:SetBucketAccessControlPolicyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetObject(struct soap *soap)
{	struct __ns1__GetObject soap_tmp___ns1__GetObject;
	_ns1__GetObjectResponse ns1__GetObjectResponse;
	ns1__GetObjectResponse.soap_default(soap);
	soap_default___ns1__GetObject(soap, &soap_tmp___ns1__GetObject);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GetObject(soap, &soap_tmp___ns1__GetObject, "-ns1:GetObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetObject(soap, soap_tmp___ns1__GetObject.ns1__GetObject, &ns1__GetObjectResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__GetObjectResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetObjectResponse.soap_put(soap, "ns1:GetObjectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetObjectResponse.soap_put(soap, "ns1:GetObjectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetObjectExtended(struct soap *soap)
{	struct __ns1__GetObjectExtended soap_tmp___ns1__GetObjectExtended;
	_ns1__GetObjectExtendedResponse ns1__GetObjectExtendedResponse;
	ns1__GetObjectExtendedResponse.soap_default(soap);
	soap_default___ns1__GetObjectExtended(soap, &soap_tmp___ns1__GetObjectExtended);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GetObjectExtended(soap, &soap_tmp___ns1__GetObjectExtended, "-ns1:GetObjectExtended", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetObjectExtended(soap, soap_tmp___ns1__GetObjectExtended.ns1__GetObjectExtended, &ns1__GetObjectExtendedResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__GetObjectExtendedResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetObjectExtendedResponse.soap_put(soap, "ns1:GetObjectExtendedResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetObjectExtendedResponse.soap_put(soap, "ns1:GetObjectExtendedResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__PutObject(struct soap *soap)
{	struct __ns1__PutObject soap_tmp___ns1__PutObject;
	_ns1__PutObjectResponse ns1__PutObjectResponse;
	ns1__PutObjectResponse.soap_default(soap);
	soap_default___ns1__PutObject(soap, &soap_tmp___ns1__PutObject);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__PutObject(soap, &soap_tmp___ns1__PutObject, "-ns1:PutObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__PutObject(soap, soap_tmp___ns1__PutObject.ns1__PutObject, &ns1__PutObjectResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__PutObjectResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__PutObjectResponse.soap_put(soap, "ns1:PutObjectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__PutObjectResponse.soap_put(soap, "ns1:PutObjectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__PutObjectInline(struct soap *soap)
{	struct __ns1__PutObjectInline soap_tmp___ns1__PutObjectInline;
	_ns1__PutObjectInlineResponse ns1__PutObjectInlineResponse;
	ns1__PutObjectInlineResponse.soap_default(soap);
	soap_default___ns1__PutObjectInline(soap, &soap_tmp___ns1__PutObjectInline);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__PutObjectInline(soap, &soap_tmp___ns1__PutObjectInline, "-ns1:PutObjectInline", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__PutObjectInline(soap, soap_tmp___ns1__PutObjectInline.ns1__PutObjectInline, &ns1__PutObjectInlineResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__PutObjectInlineResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__PutObjectInlineResponse.soap_put(soap, "ns1:PutObjectInlineResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__PutObjectInlineResponse.soap_put(soap, "ns1:PutObjectInlineResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__DeleteObject(struct soap *soap)
{	struct __ns1__DeleteObject soap_tmp___ns1__DeleteObject;
	_ns1__DeleteObjectResponse ns1__DeleteObjectResponse;
	ns1__DeleteObjectResponse.soap_default(soap);
	soap_default___ns1__DeleteObject(soap, &soap_tmp___ns1__DeleteObject);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__DeleteObject(soap, &soap_tmp___ns1__DeleteObject, "-ns1:DeleteObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__DeleteObject(soap, soap_tmp___ns1__DeleteObject.ns1__DeleteObject, &ns1__DeleteObjectResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__DeleteObjectResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__DeleteObjectResponse.soap_put(soap, "ns1:DeleteObjectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__DeleteObjectResponse.soap_put(soap, "ns1:DeleteObjectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__ListBucket(struct soap *soap)
{	struct __ns1__ListBucket soap_tmp___ns1__ListBucket;
	_ns1__ListBucketResponse ns1__ListBucketResponse;
	ns1__ListBucketResponse.soap_default(soap);
	soap_default___ns1__ListBucket(soap, &soap_tmp___ns1__ListBucket);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__ListBucket(soap, &soap_tmp___ns1__ListBucket, "-ns1:ListBucket", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__ListBucket(soap, soap_tmp___ns1__ListBucket.ns1__ListBucket, &ns1__ListBucketResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ListBucketResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ListBucketResponse.soap_put(soap, "ns1:ListBucketResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ListBucketResponse.soap_put(soap, "ns1:ListBucketResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__ListAllMyBuckets(struct soap *soap)
{	struct __ns1__ListAllMyBuckets soap_tmp___ns1__ListAllMyBuckets;
	_ns1__ListAllMyBucketsResponse ns1__ListAllMyBucketsResponse;
	ns1__ListAllMyBucketsResponse.soap_default(soap);
	soap_default___ns1__ListAllMyBuckets(soap, &soap_tmp___ns1__ListAllMyBuckets);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__ListAllMyBuckets(soap, &soap_tmp___ns1__ListAllMyBuckets, "-ns1:ListAllMyBuckets", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__ListAllMyBuckets(soap, soap_tmp___ns1__ListAllMyBuckets.ns1__ListAllMyBuckets, &ns1__ListAllMyBucketsResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__ListAllMyBucketsResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__ListAllMyBucketsResponse.soap_put(soap, "ns1:ListAllMyBucketsResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__ListAllMyBucketsResponse.soap_put(soap, "ns1:ListAllMyBucketsResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__SetBucketLoggingStatus(struct soap *soap)
{	struct __ns1__SetBucketLoggingStatus soap_tmp___ns1__SetBucketLoggingStatus;
	_ns1__SetBucketLoggingStatusResponse ns1__SetBucketLoggingStatusResponse;
	ns1__SetBucketLoggingStatusResponse.soap_default(soap);
	soap_default___ns1__SetBucketLoggingStatus(soap, &soap_tmp___ns1__SetBucketLoggingStatus);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__SetBucketLoggingStatus(soap, &soap_tmp___ns1__SetBucketLoggingStatus, "-ns1:SetBucketLoggingStatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__SetBucketLoggingStatus(soap, soap_tmp___ns1__SetBucketLoggingStatus.ns1__SetBucketLoggingStatus, &ns1__SetBucketLoggingStatusResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__SetBucketLoggingStatusResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__SetBucketLoggingStatusResponse.soap_put(soap, "ns1:SetBucketLoggingStatusResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__SetBucketLoggingStatusResponse.soap_put(soap, "ns1:SetBucketLoggingStatusResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__GetBucketLoggingStatus(struct soap *soap)
{	struct __ns1__GetBucketLoggingStatus soap_tmp___ns1__GetBucketLoggingStatus;
	_ns1__GetBucketLoggingStatusResponse ns1__GetBucketLoggingStatusResponse;
	ns1__GetBucketLoggingStatusResponse.soap_default(soap);
	soap_default___ns1__GetBucketLoggingStatus(soap, &soap_tmp___ns1__GetBucketLoggingStatus);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__GetBucketLoggingStatus(soap, &soap_tmp___ns1__GetBucketLoggingStatus, "-ns1:GetBucketLoggingStatus", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__GetBucketLoggingStatus(soap, soap_tmp___ns1__GetBucketLoggingStatus.ns1__GetBucketLoggingStatus, &ns1__GetBucketLoggingStatusResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__GetBucketLoggingStatusResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__GetBucketLoggingStatusResponse.soap_put(soap, "ns1:GetBucketLoggingStatusResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__GetBucketLoggingStatusResponse.soap_put(soap, "ns1:GetBucketLoggingStatusResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__CopyObject(struct soap *soap)
{	struct __ns1__CopyObject soap_tmp___ns1__CopyObject;
	_ns1__CopyObjectResponse ns1__CopyObjectResponse;
	ns1__CopyObjectResponse.soap_default(soap);
	soap_default___ns1__CopyObject(soap, &soap_tmp___ns1__CopyObject);
	soap->encodingStyle = NULL;
	if (!soap_get___ns1__CopyObject(soap, &soap_tmp___ns1__CopyObject, "-ns1:CopyObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __ns1__CopyObject(soap, soap_tmp___ns1__CopyObject.ns1__CopyObject, &ns1__CopyObjectResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns1__CopyObjectResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns1__CopyObjectResponse.soap_put(soap, "ns1:CopyObjectResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns1__CopyObjectResponse.soap_put(soap, "ns1:CopyObjectResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
