/* soapClient.cpp
   Generated by gSOAP 2.8.9 from AmazonS3.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.9 2012-07-12 14:05:55 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CreateBucket(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__CreateBucket *ns1__CreateBucket, _ns1__CreateBucketResponse *ns1__CreateBucketResponse)
{	struct __ns1__CreateBucket soap_tmp___ns1__CreateBucket;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__CreateBucket.ns1__CreateBucket = ns1__CreateBucket;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__CreateBucket(soap, &soap_tmp___ns1__CreateBucket);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CreateBucket(soap, &soap_tmp___ns1__CreateBucket, "-ns1:CreateBucket", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CreateBucket(soap, &soap_tmp___ns1__CreateBucket, "-ns1:CreateBucket", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CreateBucketResponse)
		return soap_closesock(soap);
	ns1__CreateBucketResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__CreateBucketResponse->soap_get(soap, "ns1:CreateBucketResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__DeleteBucket(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__DeleteBucket *ns1__DeleteBucket, _ns1__DeleteBucketResponse *ns1__DeleteBucketResponse)
{	struct __ns1__DeleteBucket soap_tmp___ns1__DeleteBucket;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DeleteBucket.ns1__DeleteBucket = ns1__DeleteBucket;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__DeleteBucket(soap, &soap_tmp___ns1__DeleteBucket);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DeleteBucket(soap, &soap_tmp___ns1__DeleteBucket, "-ns1:DeleteBucket", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DeleteBucket(soap, &soap_tmp___ns1__DeleteBucket, "-ns1:DeleteBucket", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__DeleteBucketResponse)
		return soap_closesock(soap);
	ns1__DeleteBucketResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__DeleteBucketResponse->soap_get(soap, "ns1:DeleteBucketResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetObjectAccessControlPolicy(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetObjectAccessControlPolicy *ns1__GetObjectAccessControlPolicy, _ns1__GetObjectAccessControlPolicyResponse *ns1__GetObjectAccessControlPolicyResponse)
{	struct __ns1__GetObjectAccessControlPolicy soap_tmp___ns1__GetObjectAccessControlPolicy;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetObjectAccessControlPolicy.ns1__GetObjectAccessControlPolicy = ns1__GetObjectAccessControlPolicy;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetObjectAccessControlPolicy(soap, &soap_tmp___ns1__GetObjectAccessControlPolicy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetObjectAccessControlPolicy(soap, &soap_tmp___ns1__GetObjectAccessControlPolicy, "-ns1:GetObjectAccessControlPolicy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetObjectAccessControlPolicy(soap, &soap_tmp___ns1__GetObjectAccessControlPolicy, "-ns1:GetObjectAccessControlPolicy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetObjectAccessControlPolicyResponse)
		return soap_closesock(soap);
	ns1__GetObjectAccessControlPolicyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetObjectAccessControlPolicyResponse->soap_get(soap, "ns1:GetObjectAccessControlPolicyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetBucketAccessControlPolicy(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetBucketAccessControlPolicy *ns1__GetBucketAccessControlPolicy, _ns1__GetBucketAccessControlPolicyResponse *ns1__GetBucketAccessControlPolicyResponse)
{	struct __ns1__GetBucketAccessControlPolicy soap_tmp___ns1__GetBucketAccessControlPolicy;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetBucketAccessControlPolicy.ns1__GetBucketAccessControlPolicy = ns1__GetBucketAccessControlPolicy;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetBucketAccessControlPolicy(soap, &soap_tmp___ns1__GetBucketAccessControlPolicy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetBucketAccessControlPolicy(soap, &soap_tmp___ns1__GetBucketAccessControlPolicy, "-ns1:GetBucketAccessControlPolicy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetBucketAccessControlPolicy(soap, &soap_tmp___ns1__GetBucketAccessControlPolicy, "-ns1:GetBucketAccessControlPolicy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetBucketAccessControlPolicyResponse)
		return soap_closesock(soap);
	ns1__GetBucketAccessControlPolicyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetBucketAccessControlPolicyResponse->soap_get(soap, "ns1:GetBucketAccessControlPolicyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetObjectAccessControlPolicy(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetObjectAccessControlPolicy *ns1__SetObjectAccessControlPolicy, _ns1__SetObjectAccessControlPolicyResponse *ns1__SetObjectAccessControlPolicyResponse)
{	struct __ns1__SetObjectAccessControlPolicy soap_tmp___ns1__SetObjectAccessControlPolicy;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetObjectAccessControlPolicy.ns1__SetObjectAccessControlPolicy = ns1__SetObjectAccessControlPolicy;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetObjectAccessControlPolicy(soap, &soap_tmp___ns1__SetObjectAccessControlPolicy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetObjectAccessControlPolicy(soap, &soap_tmp___ns1__SetObjectAccessControlPolicy, "-ns1:SetObjectAccessControlPolicy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetObjectAccessControlPolicy(soap, &soap_tmp___ns1__SetObjectAccessControlPolicy, "-ns1:SetObjectAccessControlPolicy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetObjectAccessControlPolicyResponse)
		return soap_closesock(soap);
	ns1__SetObjectAccessControlPolicyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetObjectAccessControlPolicyResponse->soap_get(soap, "ns1:SetObjectAccessControlPolicyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetBucketAccessControlPolicy(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetBucketAccessControlPolicy *ns1__SetBucketAccessControlPolicy, _ns1__SetBucketAccessControlPolicyResponse *ns1__SetBucketAccessControlPolicyResponse)
{	struct __ns1__SetBucketAccessControlPolicy soap_tmp___ns1__SetBucketAccessControlPolicy;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetBucketAccessControlPolicy.ns1__SetBucketAccessControlPolicy = ns1__SetBucketAccessControlPolicy;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetBucketAccessControlPolicy(soap, &soap_tmp___ns1__SetBucketAccessControlPolicy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetBucketAccessControlPolicy(soap, &soap_tmp___ns1__SetBucketAccessControlPolicy, "-ns1:SetBucketAccessControlPolicy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetBucketAccessControlPolicy(soap, &soap_tmp___ns1__SetBucketAccessControlPolicy, "-ns1:SetBucketAccessControlPolicy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetBucketAccessControlPolicyResponse)
		return soap_closesock(soap);
	ns1__SetBucketAccessControlPolicyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetBucketAccessControlPolicyResponse->soap_get(soap, "ns1:SetBucketAccessControlPolicyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetObject *ns1__GetObject, _ns1__GetObjectResponse *ns1__GetObjectResponse)
{	struct __ns1__GetObject soap_tmp___ns1__GetObject;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetObject.ns1__GetObject = ns1__GetObject;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetObject(soap, &soap_tmp___ns1__GetObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetObject(soap, &soap_tmp___ns1__GetObject, "-ns1:GetObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetObject(soap, &soap_tmp___ns1__GetObject, "-ns1:GetObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetObjectResponse)
		return soap_closesock(soap);
	ns1__GetObjectResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetObjectResponse->soap_get(soap, "ns1:GetObjectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetObjectExtended(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetObjectExtended *ns1__GetObjectExtended, _ns1__GetObjectExtendedResponse *ns1__GetObjectExtendedResponse)
{	struct __ns1__GetObjectExtended soap_tmp___ns1__GetObjectExtended;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetObjectExtended.ns1__GetObjectExtended = ns1__GetObjectExtended;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetObjectExtended(soap, &soap_tmp___ns1__GetObjectExtended);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetObjectExtended(soap, &soap_tmp___ns1__GetObjectExtended, "-ns1:GetObjectExtended", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetObjectExtended(soap, &soap_tmp___ns1__GetObjectExtended, "-ns1:GetObjectExtended", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetObjectExtendedResponse)
		return soap_closesock(soap);
	ns1__GetObjectExtendedResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetObjectExtendedResponse->soap_get(soap, "ns1:GetObjectExtendedResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__PutObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__PutObject *ns1__PutObject, _ns1__PutObjectResponse *ns1__PutObjectResponse)
{	struct __ns1__PutObject soap_tmp___ns1__PutObject;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__PutObject.ns1__PutObject = ns1__PutObject;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__PutObject(soap, &soap_tmp___ns1__PutObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__PutObject(soap, &soap_tmp___ns1__PutObject, "-ns1:PutObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__PutObject(soap, &soap_tmp___ns1__PutObject, "-ns1:PutObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__PutObjectResponse)
		return soap_closesock(soap);
	ns1__PutObjectResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__PutObjectResponse->soap_get(soap, "ns1:PutObjectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__PutObjectInline(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__PutObjectInline *ns1__PutObjectInline, _ns1__PutObjectInlineResponse *ns1__PutObjectInlineResponse)
{	struct __ns1__PutObjectInline soap_tmp___ns1__PutObjectInline;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__PutObjectInline.ns1__PutObjectInline = ns1__PutObjectInline;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__PutObjectInline(soap, &soap_tmp___ns1__PutObjectInline);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__PutObjectInline(soap, &soap_tmp___ns1__PutObjectInline, "-ns1:PutObjectInline", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__PutObjectInline(soap, &soap_tmp___ns1__PutObjectInline, "-ns1:PutObjectInline", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__PutObjectInlineResponse)
		return soap_closesock(soap);
	ns1__PutObjectInlineResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__PutObjectInlineResponse->soap_get(soap, "ns1:PutObjectInlineResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__DeleteObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse *ns1__DeleteObjectResponse)
{	struct __ns1__DeleteObject soap_tmp___ns1__DeleteObject;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DeleteObject.ns1__DeleteObject = ns1__DeleteObject;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__DeleteObject(soap, &soap_tmp___ns1__DeleteObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DeleteObject(soap, &soap_tmp___ns1__DeleteObject, "-ns1:DeleteObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DeleteObject(soap, &soap_tmp___ns1__DeleteObject, "-ns1:DeleteObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__DeleteObjectResponse)
		return soap_closesock(soap);
	ns1__DeleteObjectResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__DeleteObjectResponse->soap_get(soap, "ns1:DeleteObjectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ListBucket(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__ListBucket *ns1__ListBucket, _ns1__ListBucketResponse *ns1__ListBucketResponse)
{	struct __ns1__ListBucket soap_tmp___ns1__ListBucket;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ListBucket.ns1__ListBucket = ns1__ListBucket;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__ListBucket(soap, &soap_tmp___ns1__ListBucket);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ListBucket(soap, &soap_tmp___ns1__ListBucket, "-ns1:ListBucket", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ListBucket(soap, &soap_tmp___ns1__ListBucket, "-ns1:ListBucket", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ListBucketResponse)
		return soap_closesock(soap);
	ns1__ListBucketResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ListBucketResponse->soap_get(soap, "ns1:ListBucketResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ListAllMyBuckets(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__ListAllMyBuckets *ns1__ListAllMyBuckets, _ns1__ListAllMyBucketsResponse *ns1__ListAllMyBucketsResponse)
{	struct __ns1__ListAllMyBuckets soap_tmp___ns1__ListAllMyBuckets;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ListAllMyBuckets.ns1__ListAllMyBuckets = ns1__ListAllMyBuckets;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__ListAllMyBuckets(soap, &soap_tmp___ns1__ListAllMyBuckets);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ListAllMyBuckets(soap, &soap_tmp___ns1__ListAllMyBuckets, "-ns1:ListAllMyBuckets", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ListAllMyBuckets(soap, &soap_tmp___ns1__ListAllMyBuckets, "-ns1:ListAllMyBuckets", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ListAllMyBucketsResponse)
		return soap_closesock(soap);
	ns1__ListAllMyBucketsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ListAllMyBucketsResponse->soap_get(soap, "ns1:ListAllMyBucketsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetBucketLoggingStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__SetBucketLoggingStatus *ns1__SetBucketLoggingStatus, _ns1__SetBucketLoggingStatusResponse *ns1__SetBucketLoggingStatusResponse)
{	struct __ns1__SetBucketLoggingStatus soap_tmp___ns1__SetBucketLoggingStatus;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetBucketLoggingStatus.ns1__SetBucketLoggingStatus = ns1__SetBucketLoggingStatus;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetBucketLoggingStatus(soap, &soap_tmp___ns1__SetBucketLoggingStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetBucketLoggingStatus(soap, &soap_tmp___ns1__SetBucketLoggingStatus, "-ns1:SetBucketLoggingStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetBucketLoggingStatus(soap, &soap_tmp___ns1__SetBucketLoggingStatus, "-ns1:SetBucketLoggingStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetBucketLoggingStatusResponse)
		return soap_closesock(soap);
	ns1__SetBucketLoggingStatusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetBucketLoggingStatusResponse->soap_get(soap, "ns1:SetBucketLoggingStatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetBucketLoggingStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__GetBucketLoggingStatus *ns1__GetBucketLoggingStatus, _ns1__GetBucketLoggingStatusResponse *ns1__GetBucketLoggingStatusResponse)
{	struct __ns1__GetBucketLoggingStatus soap_tmp___ns1__GetBucketLoggingStatus;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetBucketLoggingStatus.ns1__GetBucketLoggingStatus = ns1__GetBucketLoggingStatus;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetBucketLoggingStatus(soap, &soap_tmp___ns1__GetBucketLoggingStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetBucketLoggingStatus(soap, &soap_tmp___ns1__GetBucketLoggingStatus, "-ns1:GetBucketLoggingStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetBucketLoggingStatus(soap, &soap_tmp___ns1__GetBucketLoggingStatus, "-ns1:GetBucketLoggingStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetBucketLoggingStatusResponse)
		return soap_closesock(soap);
	ns1__GetBucketLoggingStatusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetBucketLoggingStatusResponse->soap_get(soap, "ns1:GetBucketLoggingStatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__CopyObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns1__CopyObject *ns1__CopyObject, _ns1__CopyObjectResponse *ns1__CopyObjectResponse)
{	struct __ns1__CopyObject soap_tmp___ns1__CopyObject;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__CopyObject.ns1__CopyObject = ns1__CopyObject;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__CopyObject(soap, &soap_tmp___ns1__CopyObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CopyObject(soap, &soap_tmp___ns1__CopyObject, "-ns1:CopyObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CopyObject(soap, &soap_tmp___ns1__CopyObject, "-ns1:CopyObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CopyObjectResponse)
		return soap_closesock(soap);
	ns1__CopyObjectResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__CopyObjectResponse->soap_get(soap, "ns1:CopyObjectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
