/* soapAmazonS3SoapBindingProxy.h
   Generated by gSOAP 2.8.4 from AmazonS3.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapAmazonS3SoapBindingProxy_H
#define soapAmazonS3SoapBindingProxy_H
#include "soapH.h"

class SOAP_CMAC AmazonS3SoapBindingProxy
{ public:
	struct soap *soap;
	bool own;
	/// Endpoint URL of service 'AmazonS3SoapBindingProxy' (change as needed)
	const char *soap_endpoint;
	/// Constructor
	AmazonS3SoapBindingProxy();
	/// Constructor to use/share an engine state
	AmazonS3SoapBindingProxy(struct soap*);
	/// Constructor with endpoint URL
	AmazonS3SoapBindingProxy(const char *url);
	/// Constructor with engine input+output mode control
	AmazonS3SoapBindingProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	AmazonS3SoapBindingProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	AmazonS3SoapBindingProxy(soap_mode imode, soap_mode omode);
	/// Destructor frees deserialized data
	virtual	~AmazonS3SoapBindingProxy();
	/// Initializer used by constructors
	virtual	void AmazonS3SoapBindingProxy_init(soap_mode imode, soap_mode omode);
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'CreateBucket' (returns error code or SOAP_OK)
	virtual	int CreateBucket(_ns1__CreateBucket *ns1__CreateBucket, _ns1__CreateBucketResponse *ns1__CreateBucketResponse) { return CreateBucket(NULL, NULL, ns1__CreateBucket, ns1__CreateBucketResponse); }
	virtual	int CreateBucket(const char *endpoint, const char *soap_action, _ns1__CreateBucket *ns1__CreateBucket, _ns1__CreateBucketResponse *ns1__CreateBucketResponse);

	/// Web service operation 'DeleteBucket' (returns error code or SOAP_OK)
	virtual	int DeleteBucket(_ns1__DeleteBucket *ns1__DeleteBucket, _ns1__DeleteBucketResponse *ns1__DeleteBucketResponse) { return DeleteBucket(NULL, NULL, ns1__DeleteBucket, ns1__DeleteBucketResponse); }
	virtual	int DeleteBucket(const char *endpoint, const char *soap_action, _ns1__DeleteBucket *ns1__DeleteBucket, _ns1__DeleteBucketResponse *ns1__DeleteBucketResponse);

	/// Web service operation 'GetObjectAccessControlPolicy' (returns error code or SOAP_OK)
	virtual	int GetObjectAccessControlPolicy(_ns1__GetObjectAccessControlPolicy *ns1__GetObjectAccessControlPolicy, _ns1__GetObjectAccessControlPolicyResponse *ns1__GetObjectAccessControlPolicyResponse) { return GetObjectAccessControlPolicy(NULL, NULL, ns1__GetObjectAccessControlPolicy, ns1__GetObjectAccessControlPolicyResponse); }
	virtual	int GetObjectAccessControlPolicy(const char *endpoint, const char *soap_action, _ns1__GetObjectAccessControlPolicy *ns1__GetObjectAccessControlPolicy, _ns1__GetObjectAccessControlPolicyResponse *ns1__GetObjectAccessControlPolicyResponse);

	/// Web service operation 'GetBucketAccessControlPolicy' (returns error code or SOAP_OK)
	virtual	int GetBucketAccessControlPolicy(_ns1__GetBucketAccessControlPolicy *ns1__GetBucketAccessControlPolicy, _ns1__GetBucketAccessControlPolicyResponse *ns1__GetBucketAccessControlPolicyResponse) { return GetBucketAccessControlPolicy(NULL, NULL, ns1__GetBucketAccessControlPolicy, ns1__GetBucketAccessControlPolicyResponse); }
	virtual	int GetBucketAccessControlPolicy(const char *endpoint, const char *soap_action, _ns1__GetBucketAccessControlPolicy *ns1__GetBucketAccessControlPolicy, _ns1__GetBucketAccessControlPolicyResponse *ns1__GetBucketAccessControlPolicyResponse);

	/// Web service operation 'SetObjectAccessControlPolicy' (returns error code or SOAP_OK)
	virtual	int SetObjectAccessControlPolicy(_ns1__SetObjectAccessControlPolicy *ns1__SetObjectAccessControlPolicy, _ns1__SetObjectAccessControlPolicyResponse *ns1__SetObjectAccessControlPolicyResponse) { return SetObjectAccessControlPolicy(NULL, NULL, ns1__SetObjectAccessControlPolicy, ns1__SetObjectAccessControlPolicyResponse); }
	virtual	int SetObjectAccessControlPolicy(const char *endpoint, const char *soap_action, _ns1__SetObjectAccessControlPolicy *ns1__SetObjectAccessControlPolicy, _ns1__SetObjectAccessControlPolicyResponse *ns1__SetObjectAccessControlPolicyResponse);

	/// Web service operation 'SetBucketAccessControlPolicy' (returns error code or SOAP_OK)
	virtual	int SetBucketAccessControlPolicy(_ns1__SetBucketAccessControlPolicy *ns1__SetBucketAccessControlPolicy, _ns1__SetBucketAccessControlPolicyResponse *ns1__SetBucketAccessControlPolicyResponse) { return SetBucketAccessControlPolicy(NULL, NULL, ns1__SetBucketAccessControlPolicy, ns1__SetBucketAccessControlPolicyResponse); }
	virtual	int SetBucketAccessControlPolicy(const char *endpoint, const char *soap_action, _ns1__SetBucketAccessControlPolicy *ns1__SetBucketAccessControlPolicy, _ns1__SetBucketAccessControlPolicyResponse *ns1__SetBucketAccessControlPolicyResponse);

	/// Web service operation 'GetObject' (returns error code or SOAP_OK)
	virtual	int GetObject(_ns1__GetObject *ns1__GetObject, _ns1__GetObjectResponse *ns1__GetObjectResponse) { return GetObject(NULL, NULL, ns1__GetObject, ns1__GetObjectResponse); }
	virtual	int GetObject(const char *endpoint, const char *soap_action, _ns1__GetObject *ns1__GetObject, _ns1__GetObjectResponse *ns1__GetObjectResponse);

	/// Web service operation 'GetObjectExtended' (returns error code or SOAP_OK)
	virtual	int GetObjectExtended(_ns1__GetObjectExtended *ns1__GetObjectExtended, _ns1__GetObjectExtendedResponse *ns1__GetObjectExtendedResponse) { return GetObjectExtended(NULL, NULL, ns1__GetObjectExtended, ns1__GetObjectExtendedResponse); }
	virtual	int GetObjectExtended(const char *endpoint, const char *soap_action, _ns1__GetObjectExtended *ns1__GetObjectExtended, _ns1__GetObjectExtendedResponse *ns1__GetObjectExtendedResponse);

	/// Web service operation 'PutObject' (returns error code or SOAP_OK)
	virtual	int PutObject(_ns1__PutObject *ns1__PutObject, _ns1__PutObjectResponse *ns1__PutObjectResponse) { return PutObject(NULL, NULL, ns1__PutObject, ns1__PutObjectResponse); }
	virtual	int PutObject(const char *endpoint, const char *soap_action, _ns1__PutObject *ns1__PutObject, _ns1__PutObjectResponse *ns1__PutObjectResponse);

	/// Web service operation 'PutObjectInline' (returns error code or SOAP_OK)
	virtual	int PutObjectInline(_ns1__PutObjectInline *ns1__PutObjectInline, _ns1__PutObjectInlineResponse *ns1__PutObjectInlineResponse) { return PutObjectInline(NULL, NULL, ns1__PutObjectInline, ns1__PutObjectInlineResponse); }
	virtual	int PutObjectInline(const char *endpoint, const char *soap_action, _ns1__PutObjectInline *ns1__PutObjectInline, _ns1__PutObjectInlineResponse *ns1__PutObjectInlineResponse);

	/// Web service operation 'DeleteObject' (returns error code or SOAP_OK)
	virtual	int DeleteObject(_ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse *ns1__DeleteObjectResponse) { return DeleteObject(NULL, NULL, ns1__DeleteObject, ns1__DeleteObjectResponse); }
	virtual	int DeleteObject(const char *endpoint, const char *soap_action, _ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse *ns1__DeleteObjectResponse);

	/// Web service operation 'ListBucket' (returns error code or SOAP_OK)
	virtual	int ListBucket(_ns1__ListBucket *ns1__ListBucket, _ns1__ListBucketResponse *ns1__ListBucketResponse) { return ListBucket(NULL, NULL, ns1__ListBucket, ns1__ListBucketResponse); }
	virtual	int ListBucket(const char *endpoint, const char *soap_action, _ns1__ListBucket *ns1__ListBucket, _ns1__ListBucketResponse *ns1__ListBucketResponse);

	/// Web service operation 'ListAllMyBuckets' (returns error code or SOAP_OK)
	virtual	int ListAllMyBuckets(_ns1__ListAllMyBuckets *ns1__ListAllMyBuckets, _ns1__ListAllMyBucketsResponse *ns1__ListAllMyBucketsResponse) { return ListAllMyBuckets(NULL, NULL, ns1__ListAllMyBuckets, ns1__ListAllMyBucketsResponse); }
	virtual	int ListAllMyBuckets(const char *endpoint, const char *soap_action, _ns1__ListAllMyBuckets *ns1__ListAllMyBuckets, _ns1__ListAllMyBucketsResponse *ns1__ListAllMyBucketsResponse);

	/// Web service operation 'SetBucketLoggingStatus' (returns error code or SOAP_OK)
	virtual	int SetBucketLoggingStatus(_ns1__SetBucketLoggingStatus *ns1__SetBucketLoggingStatus, _ns1__SetBucketLoggingStatusResponse *ns1__SetBucketLoggingStatusResponse) { return SetBucketLoggingStatus(NULL, NULL, ns1__SetBucketLoggingStatus, ns1__SetBucketLoggingStatusResponse); }
	virtual	int SetBucketLoggingStatus(const char *endpoint, const char *soap_action, _ns1__SetBucketLoggingStatus *ns1__SetBucketLoggingStatus, _ns1__SetBucketLoggingStatusResponse *ns1__SetBucketLoggingStatusResponse);

	/// Web service operation 'GetBucketLoggingStatus' (returns error code or SOAP_OK)
	virtual	int GetBucketLoggingStatus(_ns1__GetBucketLoggingStatus *ns1__GetBucketLoggingStatus, _ns1__GetBucketLoggingStatusResponse *ns1__GetBucketLoggingStatusResponse) { return GetBucketLoggingStatus(NULL, NULL, ns1__GetBucketLoggingStatus, ns1__GetBucketLoggingStatusResponse); }
	virtual	int GetBucketLoggingStatus(const char *endpoint, const char *soap_action, _ns1__GetBucketLoggingStatus *ns1__GetBucketLoggingStatus, _ns1__GetBucketLoggingStatusResponse *ns1__GetBucketLoggingStatusResponse);

	/// Web service operation 'CopyObject' (returns error code or SOAP_OK)
	virtual	int CopyObject(_ns1__CopyObject *ns1__CopyObject, _ns1__CopyObjectResponse *ns1__CopyObjectResponse) { return CopyObject(NULL, NULL, ns1__CopyObject, ns1__CopyObjectResponse); }
	virtual	int CopyObject(const char *endpoint, const char *soap_action, _ns1__CopyObject *ns1__CopyObject, _ns1__CopyObjectResponse *ns1__CopyObjectResponse);
};
#endif
