/* soapAmazonS3SoapBindingProxy.cpp
   Generated by gSOAP 2.8.4 from AmazonS3.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#include "soapAmazonS3SoapBindingProxy.h"

AmazonS3SoapBindingProxy::AmazonS3SoapBindingProxy()
{	this->soap = soap_new();
	this->own = true;
	AmazonS3SoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

AmazonS3SoapBindingProxy::AmazonS3SoapBindingProxy(struct soap *_soap)
{	this->soap = _soap;
	this->own = false;
	AmazonS3SoapBindingProxy_init(_soap->imode, _soap->omode);
}

AmazonS3SoapBindingProxy::AmazonS3SoapBindingProxy(const char *url)
{	this->soap = soap_new();
	this->own = true;
	AmazonS3SoapBindingProxy_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
	soap_endpoint = url;
}

AmazonS3SoapBindingProxy::AmazonS3SoapBindingProxy(soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	AmazonS3SoapBindingProxy_init(iomode, iomode);
}

AmazonS3SoapBindingProxy::AmazonS3SoapBindingProxy(const char *url, soap_mode iomode)
{	this->soap = soap_new();
	this->own = true;
	AmazonS3SoapBindingProxy_init(iomode, iomode);
	soap_endpoint = url;
}

AmazonS3SoapBindingProxy::AmazonS3SoapBindingProxy(soap_mode imode, soap_mode omode)
{	this->soap = soap_new();
	this->own = true;
	AmazonS3SoapBindingProxy_init(imode, omode);
}

AmazonS3SoapBindingProxy::~AmazonS3SoapBindingProxy()
{	if (this->own)
		soap_free(this->soap);
}

void AmazonS3SoapBindingProxy::AmazonS3SoapBindingProxy_init(soap_mode imode, soap_mode omode)
{	soap_imode(this->soap, imode);
	soap_omode(this->soap, omode);
	soap_endpoint = NULL;
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns1", "http://s3.amazonaws.com/doc/2006-03-01/", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap_set_namespaces(this->soap, namespaces);
}

void AmazonS3SoapBindingProxy::destroy()
{	soap_destroy(this->soap);
	soap_end(this->soap);
}

void AmazonS3SoapBindingProxy::soap_noheader()
{	this->soap->header = NULL;
}

const SOAP_ENV__Header *AmazonS3SoapBindingProxy::soap_header()
{	return this->soap->header;
}

const SOAP_ENV__Fault *AmazonS3SoapBindingProxy::soap_fault()
{	return this->soap->fault;
}

const char *AmazonS3SoapBindingProxy::soap_fault_string()
{	return *soap_faultstring(this->soap);
}

const char *AmazonS3SoapBindingProxy::soap_fault_detail()
{	return *soap_faultdetail(this->soap);
}

int AmazonS3SoapBindingProxy::soap_close_socket()
{	return soap_closesock(this->soap);
}

int AmazonS3SoapBindingProxy::soap_force_close_socket()
{	return soap_force_closesock(this->soap);
}

void AmazonS3SoapBindingProxy::soap_print_fault(FILE *fd)
{	::soap_print_fault(this->soap, fd);
}

#ifndef WITH_LEAN
void AmazonS3SoapBindingProxy::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this->soap, os);
}

char *AmazonS3SoapBindingProxy::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this->soap, buf, len);
}
#endif

int AmazonS3SoapBindingProxy::CreateBucket(const char *endpoint, const char *soap_action, _ns1__CreateBucket *ns1__CreateBucket, _ns1__CreateBucketResponse *ns1__CreateBucketResponse)
{	struct soap *soap = this->soap;
	struct __ns1__CreateBucket soap_tmp___ns1__CreateBucket;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__CreateBucket.ns1__CreateBucket = ns1__CreateBucket;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__CreateBucket(soap, &soap_tmp___ns1__CreateBucket);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CreateBucket(soap, &soap_tmp___ns1__CreateBucket, "-ns1:CreateBucket", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CreateBucket(soap, &soap_tmp___ns1__CreateBucket, "-ns1:CreateBucket", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CreateBucketResponse)
		return soap_closesock(soap);
	ns1__CreateBucketResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__CreateBucketResponse->soap_get(soap, "ns1:CreateBucketResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::DeleteBucket(const char *endpoint, const char *soap_action, _ns1__DeleteBucket *ns1__DeleteBucket, _ns1__DeleteBucketResponse *ns1__DeleteBucketResponse)
{	struct soap *soap = this->soap;
	struct __ns1__DeleteBucket soap_tmp___ns1__DeleteBucket;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DeleteBucket.ns1__DeleteBucket = ns1__DeleteBucket;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__DeleteBucket(soap, &soap_tmp___ns1__DeleteBucket);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DeleteBucket(soap, &soap_tmp___ns1__DeleteBucket, "-ns1:DeleteBucket", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DeleteBucket(soap, &soap_tmp___ns1__DeleteBucket, "-ns1:DeleteBucket", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__DeleteBucketResponse)
		return soap_closesock(soap);
	ns1__DeleteBucketResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__DeleteBucketResponse->soap_get(soap, "ns1:DeleteBucketResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::GetObjectAccessControlPolicy(const char *endpoint, const char *soap_action, _ns1__GetObjectAccessControlPolicy *ns1__GetObjectAccessControlPolicy, _ns1__GetObjectAccessControlPolicyResponse *ns1__GetObjectAccessControlPolicyResponse)
{	struct soap *soap = this->soap;
	struct __ns1__GetObjectAccessControlPolicy soap_tmp___ns1__GetObjectAccessControlPolicy;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetObjectAccessControlPolicy.ns1__GetObjectAccessControlPolicy = ns1__GetObjectAccessControlPolicy;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetObjectAccessControlPolicy(soap, &soap_tmp___ns1__GetObjectAccessControlPolicy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetObjectAccessControlPolicy(soap, &soap_tmp___ns1__GetObjectAccessControlPolicy, "-ns1:GetObjectAccessControlPolicy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetObjectAccessControlPolicy(soap, &soap_tmp___ns1__GetObjectAccessControlPolicy, "-ns1:GetObjectAccessControlPolicy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetObjectAccessControlPolicyResponse)
		return soap_closesock(soap);
	ns1__GetObjectAccessControlPolicyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetObjectAccessControlPolicyResponse->soap_get(soap, "ns1:GetObjectAccessControlPolicyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::GetBucketAccessControlPolicy(const char *endpoint, const char *soap_action, _ns1__GetBucketAccessControlPolicy *ns1__GetBucketAccessControlPolicy, _ns1__GetBucketAccessControlPolicyResponse *ns1__GetBucketAccessControlPolicyResponse)
{	struct soap *soap = this->soap;
	struct __ns1__GetBucketAccessControlPolicy soap_tmp___ns1__GetBucketAccessControlPolicy;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetBucketAccessControlPolicy.ns1__GetBucketAccessControlPolicy = ns1__GetBucketAccessControlPolicy;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetBucketAccessControlPolicy(soap, &soap_tmp___ns1__GetBucketAccessControlPolicy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetBucketAccessControlPolicy(soap, &soap_tmp___ns1__GetBucketAccessControlPolicy, "-ns1:GetBucketAccessControlPolicy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetBucketAccessControlPolicy(soap, &soap_tmp___ns1__GetBucketAccessControlPolicy, "-ns1:GetBucketAccessControlPolicy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetBucketAccessControlPolicyResponse)
		return soap_closesock(soap);
	ns1__GetBucketAccessControlPolicyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetBucketAccessControlPolicyResponse->soap_get(soap, "ns1:GetBucketAccessControlPolicyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::SetObjectAccessControlPolicy(const char *endpoint, const char *soap_action, _ns1__SetObjectAccessControlPolicy *ns1__SetObjectAccessControlPolicy, _ns1__SetObjectAccessControlPolicyResponse *ns1__SetObjectAccessControlPolicyResponse)
{	struct soap *soap = this->soap;
	struct __ns1__SetObjectAccessControlPolicy soap_tmp___ns1__SetObjectAccessControlPolicy;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetObjectAccessControlPolicy.ns1__SetObjectAccessControlPolicy = ns1__SetObjectAccessControlPolicy;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetObjectAccessControlPolicy(soap, &soap_tmp___ns1__SetObjectAccessControlPolicy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetObjectAccessControlPolicy(soap, &soap_tmp___ns1__SetObjectAccessControlPolicy, "-ns1:SetObjectAccessControlPolicy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetObjectAccessControlPolicy(soap, &soap_tmp___ns1__SetObjectAccessControlPolicy, "-ns1:SetObjectAccessControlPolicy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetObjectAccessControlPolicyResponse)
		return soap_closesock(soap);
	ns1__SetObjectAccessControlPolicyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetObjectAccessControlPolicyResponse->soap_get(soap, "ns1:SetObjectAccessControlPolicyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::SetBucketAccessControlPolicy(const char *endpoint, const char *soap_action, _ns1__SetBucketAccessControlPolicy *ns1__SetBucketAccessControlPolicy, _ns1__SetBucketAccessControlPolicyResponse *ns1__SetBucketAccessControlPolicyResponse)
{	struct soap *soap = this->soap;
	struct __ns1__SetBucketAccessControlPolicy soap_tmp___ns1__SetBucketAccessControlPolicy;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetBucketAccessControlPolicy.ns1__SetBucketAccessControlPolicy = ns1__SetBucketAccessControlPolicy;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetBucketAccessControlPolicy(soap, &soap_tmp___ns1__SetBucketAccessControlPolicy);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetBucketAccessControlPolicy(soap, &soap_tmp___ns1__SetBucketAccessControlPolicy, "-ns1:SetBucketAccessControlPolicy", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetBucketAccessControlPolicy(soap, &soap_tmp___ns1__SetBucketAccessControlPolicy, "-ns1:SetBucketAccessControlPolicy", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetBucketAccessControlPolicyResponse)
		return soap_closesock(soap);
	ns1__SetBucketAccessControlPolicyResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetBucketAccessControlPolicyResponse->soap_get(soap, "ns1:SetBucketAccessControlPolicyResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::GetObject(const char *endpoint, const char *soap_action, _ns1__GetObject *ns1__GetObject, _ns1__GetObjectResponse *ns1__GetObjectResponse)
{	struct soap *soap = this->soap;
	struct __ns1__GetObject soap_tmp___ns1__GetObject;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetObject.ns1__GetObject = ns1__GetObject;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetObject(soap, &soap_tmp___ns1__GetObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetObject(soap, &soap_tmp___ns1__GetObject, "-ns1:GetObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetObject(soap, &soap_tmp___ns1__GetObject, "-ns1:GetObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetObjectResponse)
		return soap_closesock(soap);
	ns1__GetObjectResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetObjectResponse->soap_get(soap, "ns1:GetObjectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::GetObjectExtended(const char *endpoint, const char *soap_action, _ns1__GetObjectExtended *ns1__GetObjectExtended, _ns1__GetObjectExtendedResponse *ns1__GetObjectExtendedResponse)
{	struct soap *soap = this->soap;
	struct __ns1__GetObjectExtended soap_tmp___ns1__GetObjectExtended;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetObjectExtended.ns1__GetObjectExtended = ns1__GetObjectExtended;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetObjectExtended(soap, &soap_tmp___ns1__GetObjectExtended);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetObjectExtended(soap, &soap_tmp___ns1__GetObjectExtended, "-ns1:GetObjectExtended", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetObjectExtended(soap, &soap_tmp___ns1__GetObjectExtended, "-ns1:GetObjectExtended", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetObjectExtendedResponse)
		return soap_closesock(soap);
	ns1__GetObjectExtendedResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetObjectExtendedResponse->soap_get(soap, "ns1:GetObjectExtendedResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::PutObject(const char *endpoint, const char *soap_action, _ns1__PutObject *ns1__PutObject, _ns1__PutObjectResponse *ns1__PutObjectResponse)
{	struct soap *soap = this->soap;
	struct __ns1__PutObject soap_tmp___ns1__PutObject;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__PutObject.ns1__PutObject = ns1__PutObject;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__PutObject(soap, &soap_tmp___ns1__PutObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__PutObject(soap, &soap_tmp___ns1__PutObject, "-ns1:PutObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__PutObject(soap, &soap_tmp___ns1__PutObject, "-ns1:PutObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__PutObjectResponse)
		return soap_closesock(soap);
	ns1__PutObjectResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__PutObjectResponse->soap_get(soap, "ns1:PutObjectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::PutObjectInline(const char *endpoint, const char *soap_action, _ns1__PutObjectInline *ns1__PutObjectInline, _ns1__PutObjectInlineResponse *ns1__PutObjectInlineResponse)
{	struct soap *soap = this->soap;
	struct __ns1__PutObjectInline soap_tmp___ns1__PutObjectInline;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__PutObjectInline.ns1__PutObjectInline = ns1__PutObjectInline;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__PutObjectInline(soap, &soap_tmp___ns1__PutObjectInline);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__PutObjectInline(soap, &soap_tmp___ns1__PutObjectInline, "-ns1:PutObjectInline", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__PutObjectInline(soap, &soap_tmp___ns1__PutObjectInline, "-ns1:PutObjectInline", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__PutObjectInlineResponse)
		return soap_closesock(soap);
	ns1__PutObjectInlineResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__PutObjectInlineResponse->soap_get(soap, "ns1:PutObjectInlineResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::DeleteObject(const char *endpoint, const char *soap_action, _ns1__DeleteObject *ns1__DeleteObject, _ns1__DeleteObjectResponse *ns1__DeleteObjectResponse)
{	struct soap *soap = this->soap;
	struct __ns1__DeleteObject soap_tmp___ns1__DeleteObject;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__DeleteObject.ns1__DeleteObject = ns1__DeleteObject;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__DeleteObject(soap, &soap_tmp___ns1__DeleteObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__DeleteObject(soap, &soap_tmp___ns1__DeleteObject, "-ns1:DeleteObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__DeleteObject(soap, &soap_tmp___ns1__DeleteObject, "-ns1:DeleteObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__DeleteObjectResponse)
		return soap_closesock(soap);
	ns1__DeleteObjectResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__DeleteObjectResponse->soap_get(soap, "ns1:DeleteObjectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::ListBucket(const char *endpoint, const char *soap_action, _ns1__ListBucket *ns1__ListBucket, _ns1__ListBucketResponse *ns1__ListBucketResponse)
{	struct soap *soap = this->soap;
	struct __ns1__ListBucket soap_tmp___ns1__ListBucket;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ListBucket.ns1__ListBucket = ns1__ListBucket;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__ListBucket(soap, &soap_tmp___ns1__ListBucket);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ListBucket(soap, &soap_tmp___ns1__ListBucket, "-ns1:ListBucket", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ListBucket(soap, &soap_tmp___ns1__ListBucket, "-ns1:ListBucket", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ListBucketResponse)
		return soap_closesock(soap);
	ns1__ListBucketResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ListBucketResponse->soap_get(soap, "ns1:ListBucketResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::ListAllMyBuckets(const char *endpoint, const char *soap_action, _ns1__ListAllMyBuckets *ns1__ListAllMyBuckets, _ns1__ListAllMyBucketsResponse *ns1__ListAllMyBucketsResponse)
{	struct soap *soap = this->soap;
	struct __ns1__ListAllMyBuckets soap_tmp___ns1__ListAllMyBuckets;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ListAllMyBuckets.ns1__ListAllMyBuckets = ns1__ListAllMyBuckets;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__ListAllMyBuckets(soap, &soap_tmp___ns1__ListAllMyBuckets);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ListAllMyBuckets(soap, &soap_tmp___ns1__ListAllMyBuckets, "-ns1:ListAllMyBuckets", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ListAllMyBuckets(soap, &soap_tmp___ns1__ListAllMyBuckets, "-ns1:ListAllMyBuckets", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__ListAllMyBucketsResponse)
		return soap_closesock(soap);
	ns1__ListAllMyBucketsResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__ListAllMyBucketsResponse->soap_get(soap, "ns1:ListAllMyBucketsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::SetBucketLoggingStatus(const char *endpoint, const char *soap_action, _ns1__SetBucketLoggingStatus *ns1__SetBucketLoggingStatus, _ns1__SetBucketLoggingStatusResponse *ns1__SetBucketLoggingStatusResponse)
{	struct soap *soap = this->soap;
	struct __ns1__SetBucketLoggingStatus soap_tmp___ns1__SetBucketLoggingStatus;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetBucketLoggingStatus.ns1__SetBucketLoggingStatus = ns1__SetBucketLoggingStatus;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__SetBucketLoggingStatus(soap, &soap_tmp___ns1__SetBucketLoggingStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetBucketLoggingStatus(soap, &soap_tmp___ns1__SetBucketLoggingStatus, "-ns1:SetBucketLoggingStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetBucketLoggingStatus(soap, &soap_tmp___ns1__SetBucketLoggingStatus, "-ns1:SetBucketLoggingStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__SetBucketLoggingStatusResponse)
		return soap_closesock(soap);
	ns1__SetBucketLoggingStatusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__SetBucketLoggingStatusResponse->soap_get(soap, "ns1:SetBucketLoggingStatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::GetBucketLoggingStatus(const char *endpoint, const char *soap_action, _ns1__GetBucketLoggingStatus *ns1__GetBucketLoggingStatus, _ns1__GetBucketLoggingStatusResponse *ns1__GetBucketLoggingStatusResponse)
{	struct soap *soap = this->soap;
	struct __ns1__GetBucketLoggingStatus soap_tmp___ns1__GetBucketLoggingStatus;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetBucketLoggingStatus.ns1__GetBucketLoggingStatus = ns1__GetBucketLoggingStatus;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__GetBucketLoggingStatus(soap, &soap_tmp___ns1__GetBucketLoggingStatus);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetBucketLoggingStatus(soap, &soap_tmp___ns1__GetBucketLoggingStatus, "-ns1:GetBucketLoggingStatus", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetBucketLoggingStatus(soap, &soap_tmp___ns1__GetBucketLoggingStatus, "-ns1:GetBucketLoggingStatus", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__GetBucketLoggingStatusResponse)
		return soap_closesock(soap);
	ns1__GetBucketLoggingStatusResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__GetBucketLoggingStatusResponse->soap_get(soap, "ns1:GetBucketLoggingStatusResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

int AmazonS3SoapBindingProxy::CopyObject(const char *endpoint, const char *soap_action, _ns1__CopyObject *ns1__CopyObject, _ns1__CopyObjectResponse *ns1__CopyObjectResponse)
{	struct soap *soap = this->soap;
	struct __ns1__CopyObject soap_tmp___ns1__CopyObject;
	if (endpoint)
		soap_endpoint = endpoint;
	if (!soap_endpoint)
		soap_endpoint = "https://s3.amazonaws.com/soap";
	if (!soap_action)
		soap_action = "";
	soap->encodingStyle = NULL;
	soap_tmp___ns1__CopyObject.ns1__CopyObject = ns1__CopyObject;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___ns1__CopyObject(soap, &soap_tmp___ns1__CopyObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__CopyObject(soap, &soap_tmp___ns1__CopyObject, "-ns1:CopyObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__CopyObject(soap, &soap_tmp___ns1__CopyObject, "-ns1:CopyObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns1__CopyObjectResponse)
		return soap_closesock(soap);
	ns1__CopyObjectResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns1__CopyObjectResponse->soap_get(soap, "ns1:CopyObjectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
/* End of client proxy code */
